---
title: 'Analysis 1: Pathway Comparison'
author: "Zofia Radwańska"
date: "2026-05-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#loading in the packages
```{r}
library(pacman)
pacman::p_load(tidyverse,
               readr,
               dplyr,
               ggplot2,
               sf
               )
```

#loading in the data
```{r}
#pathways
file_paths <- list.files(path = "/Users/zofiaradwanska/Desktop/Spatial_Analytics/exam/bird-dataset-main/data/normalized_trajectories", full.names = TRUE) 

#extract participant id
trajectory_normalised <- file_paths %>%
  set_names() %>%
  map_df(~read_csv(.x, col_types = cols()), .id = "file_path") %>%
  # extract participant id from the file name
  mutate(participant_id = str_extract(file_path, "\\d{12}")) %>%
  select(-file_path)

#write.csv(trajectory_normalised,"~/Downloads/all_trajectories_normalised.csv", row.names = FALSE)

geo_trajectories <- st_read("/Users/zofiaradwanska/Desktop/Spatial_Analytics/SpatialAnalytics_new/data/geojson_converted_objects/all_trajectories_norm.geojson")

head(trajectory_normalised)
nrow(trajectory_normalised)

#floor plan
floor_0_plan_sf <- st_read("/Users/zofiaradwanska/Desktop/Spatial_Analytics/SpatialAnalytics_new/data/polygons/polygons_floor_0.geojson")
floor_1_plan_sf <- st_read("/Users/zofiaradwanska/Desktop/Spatial_Analytics/SpatialAnalytics_new/data/polygons/polygons_floor_1.geojson")
floor_2_plan_sf <- st_read("/Users/zofiaradwanska/Desktop/Spatial_Analytics/SpatialAnalytics_new/data/polygons/polygons_floor_2.geojson")

plot(st_geometry(floor_0_plan_sf), main = "Museum Floor Plan", col = "black")
```

```{r}
unique(floor_0_plan_sf$object_type) #unique types of elements in the plan
```
#division of trajectories into separate floor files
```{r}
traj_sf <- trajectory_normalised %>%
  st_as_sf(coords = c("x", "y"), crs = NA)

trajectory_f00 <- traj_sf %>% 
  mutate("floorNumber" == 0)
trajectory_f01 <- traj_sf %>% 
  mutate("floorNumber" == 1)
trajectory_f02 <- traj_sf %>% 
  mutate("floorNumber" == 2)
```

```{r}
plot(floor_0_plan_sf$geometry)

plot(geo_trajectories$geometry)
```


```{r}
# Basic plot: trajectories colored by participant
ggplot() +
  # Floor plan as background
  geom_sf(data = floor_0_plan_sf,
          fill = "white", color = "black", linewidth = 0.3) +
  
  # Visitor pathways - different color per participant
  geom_path(data = trajectory_f00,
            aes(x = x, y = y, color = factor(participant_id), group = participant_id),
            alpha = 0.6, size = 0.5) +
  coord_fixed() +
  
  # Styling
  theme_minimal() +
  coord_fixed() +
  labs(
    title = "Visitor Pathways - Museum Floor Plan",
    color = "Participant ID",
    x = "X Coordinate", y = "Y Coordinate"
  ) +
  theme(
    panel.background = element_rect(fill = "lightgray", color = NA),
    plot.background = element_rect(fill = "white")
  )
```



